---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: new
  name: new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new
  template:
    metadata:
      labels:
        app: new
    spec:
      containers:
      - image: krishna1952/new:1.0
        imagePullPolicy: Always
        name: new

